[package]
name = "kercat"
version = "0.1.2"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-std-resolver = "0.23.0"
clap = "3.2"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.20"
trust-dns-resolver = "0.23.0"
